"""codegen blocks — incremental, within-module code generation.

A module is generated as a frozen skeleton (the .hbs interface + a .cbs
preamble) produced ONCE, then one function body at a time, compiling after
each. This avoids the whole-file timeout (each gen is one small function) and
lets a compile error localize to — and regenerate — a single function instead
of the whole module. The .cbs is rebuilt from the accumulated bodies each write,
so regenerating a function REPLACES its body (no duplicate definitions).

  codegen.plan        group contracts into modules (units = modules)
  codegen.skel_write  persist + write the module skeleton (.hbs + .cbs head)
  codegen.seed_units  one codegen_units row per function (pending)
  codegen.next_fn     pick the next pending function -> active  (next | done)
  codegen.write_fn    store the active function's body, rebuild the .cbs
  codegen.mark_done   active -> done (its compile went green)
"""
from __future__ import annotations

from pathlib import Path

from forgeflow.blocks import block


def _fk(task):
    return (task.get("payload") or {}).get("feature_key")


def _worktree(ctx, task):
    """This task+attempt's worktree — the deterministic path worktree.create used."""
    return Path(ctx["_workspaces_dir"]) / ("task-%d-a%d" % (task["id"], task["attempts"]))


@block("codegen.plan", "state", {"ok", "empty"})
def codegen_plan(ctx, task, prev):
    """Group the feature's contracts into codegen UNITS = modules. Functions in
    one module share the struct, helpers, and internal calls, so a module is the
    smallest thing that can be generated coherently. A single-module feature is
    one unit (generated by the per-function loop below); a multi-module feature
    fans out one loop per module (fanout.emit + join — the identified
    enhancement, unneeded until a feature spans modules)."""
    conn = ctx["_conn"]
    rows = conn.execute(
        "SELECT c.module, c.impl_file FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.status='active'", (_fk(task),)).fetchall()
    mods = {}
    for m, impl in rows:
        mods[m or impl or "default"] = mods.get(m or impl or "default", 0) + 1
    if not mods:
        return "empty", {}
    units = [{"module": m, "contract_count": n} for m, n in sorted(mods.items())]
    return "ok", {"units": units, "unit_count": len(units)}


@block("codegen.skel_write", "state", {"ok", "empty"})
def codegen_skel_write(ctx, task, prev):
    """Persist the module skeleton (from the skeleton agent) and write the .hbs
    interface + the .cbs preamble into the worktree. Paths derive from the
    module's impl_file (.cbs) with .hbs alongside."""
    conn = ctx["_conn"]
    fk = _fk(task)
    hbs = (prev or {}).get("hbs")
    cbs_head = (prev or {}).get("cbs_head") or ""
    if not hbs:
        return "empty", {}
    r = conn.execute(
        "SELECT c.module, c.impl_file FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.impl_file IS NOT NULL LIMIT 1", (fk,)).fetchone()
    module = (r[0] if r else None) or "default"
    cbs_path = (r[1] if r else None) or ("src/%s.cbs" % module)
    hbs_path = cbs_path.rsplit(".", 1)[0] + ".hbs"
    conn.execute("DELETE FROM codegen_modules WHERE feature_key=? AND module=?", (fk, module))
    conn.execute(
        "INSERT INTO codegen_modules(feature_key, module, hbs_path, cbs_path, hbs, cbs_head)"
        " VALUES (?,?,?,?,?,?)", (fk, module, hbs_path, cbs_path, hbs, cbs_head))
    root = _worktree(ctx, task)
    (root / hbs_path).parent.mkdir(parents=True, exist_ok=True)
    (root / hbs_path).write_text(hbs)
    (root / cbs_path).write_text(cbs_head.rstrip() + "\n")
    return "ok", {"module": module, "hbs_path": hbs_path, "cbs_path": cbs_path}


@block("codegen.need_skeleton", "state", {"build", "reuse"})
def codegen_need_skeleton(ctx, task, prev):
    """Is there a cached skeleton for this feature? 'reuse' on a modification
    (skeleton survived; reconcile drops it only on a signature change), 'build'
    on a first run or after a signature change."""
    row = ctx["_conn"].execute(
        "SELECT 1 FROM codegen_modules WHERE feature_key=? LIMIT 1", (_fk(task),)).fetchone()
    return ("reuse" if row else "build"), {}


def _rebuild_cbs(conn, fk, module, root, cbs_path, cbs_head):
    """.cbs = the module's preamble + that MODULE's bodies (never another's)."""
    bodies = [b for (b,) in conn.execute(
        "SELECT body FROM codegen_units WHERE feature_key=? AND module=?"
        " AND body IS NOT NULL ORDER BY seq", (fk, module))]
    cbs = cbs_head.rstrip() + ("\n\n" + "\n\n".join(b.strip() for b in bodies) + "\n"
                               if bodies else "\n")
    dest = root / cbs_path
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(cbs)
    return len(bodies)


@block("codegen.rehydrate", "state", {"ok", "empty"})
def codegen_rehydrate(ctx, task, prev):
    """A modification runs in a FRESH worktree. Restore EVERY cached module from
    the DB (its .hbs + a .cbs rebuilt from that module's done bodies), so the
    per-function loop only regenerates the units reconcile marked pending."""
    conn = ctx["_conn"]
    fk = _fk(task)
    rows = conn.execute("SELECT module, hbs_path, cbs_path, hbs, cbs_head"
                        " FROM codegen_modules WHERE feature_key=?", (fk,)).fetchall()
    if not rows:
        return "empty", {}
    root = _worktree(ctx, task)
    restored = 0
    for module, hbs_path, cbs_path, hbs, cbs_head in rows:
        (root / hbs_path).parent.mkdir(parents=True, exist_ok=True)
        (root / hbs_path).write_text(hbs)
        restored += _rebuild_cbs(conn, fk, module, root, cbs_path, cbs_head)
    return "ok", {"modules": len(rows), "rehydrated_bodies": restored}


@block("codegen.seed_units", "state", {"ok", "empty"})
def codegen_seed_units(ctx, task, prev):
    """Ensure a codegen_units row per active contract — IDEMPOTENT across runs:
    new contracts get a pending unit; existing units keep whatever status
    reconcile left (done stays done, changed is pending); contracts no longer
    active are dropped. This is what makes a modification re-gen only the deltas."""
    conn = ctx["_conn"]
    fk = _fk(task)
    rows = conn.execute(
        "SELECT c.contract_key, c.module FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.status='active' ORDER BY c.id", (fk,)).fetchall()
    if not rows:
        return "empty", {}
    existing = {ck for (ck,) in conn.execute(
        "SELECT contract_key FROM codegen_units WHERE feature_key=?", (fk,))}
    active = []
    for i, (ck, mod) in enumerate(rows):
        active.append(ck)
        if ck in existing:
            conn.execute("UPDATE codegen_units SET seq=? WHERE feature_key=? AND contract_key=?",
                         (i, fk, ck))
        else:
            conn.execute(
                "INSERT INTO codegen_units(feature_key, module, contract_key, seq, status)"
                " VALUES (?,?,?,?, 'pending')", (fk, mod or "default", ck, i))
    conn.execute("DELETE FROM codegen_units WHERE feature_key=? AND contract_key NOT IN (%s)"
                 % ",".join("?" * len(active)), [fk] + active)
    pending = conn.execute("SELECT count(*) FROM codegen_units"
                           " WHERE feature_key=? AND status='pending'", (fk,)).fetchone()[0]
    return "ok", {"units": len(rows), "pending": pending}


@block("codegen.next_fn", "state", {"next", "done"})
def codegen_next_fn(ctx, task, prev):
    """Advance the cursor: the current 'active' function (a red retry re-enters
    here only via mark_done, so normally none is active) or the next 'pending'
    one. 'done' when every unit is generated + compiled green."""
    conn = ctx["_conn"]
    fk = _fk(task)
    row = conn.execute(
        "SELECT contract_key FROM codegen_units WHERE feature_key=? AND status='active'"
        " ORDER BY seq LIMIT 1", (fk,)).fetchone()
    if not row:
        row = conn.execute(
            "SELECT contract_key FROM codegen_units WHERE feature_key=? AND status='pending'"
            " ORDER BY seq LIMIT 1", (fk,)).fetchone()
        if not row:
            return "done", {}
        conn.execute("UPDATE codegen_units SET status='active'"
                     " WHERE feature_key=? AND contract_key=?", (fk, row[0]))
    remaining = conn.execute(
        "SELECT count(*) FROM codegen_units WHERE feature_key=? AND status!='done'",
        (fk,)).fetchone()[0]
    return "next", {"contract_key": row[0], "remaining": remaining}


@block("codegen.write_fn", "state", {"ok", "empty"})
def codegen_write_fn(ctx, task, prev):
    """Store the active function's body, then rebuild ITS MODULE's .cbs from that
    module's bodies (never another module's). Rebuilding (vs appending) means a
    regenerate cleanly REPLACES the active function's body."""
    conn = ctx["_conn"]
    fk = _fk(task)
    body = (prev or {}).get("body")
    if not body:
        files = (prev or {}).get("files") or []
        body = files[0].get("content") if files and isinstance(files[0], dict) else None
    if not body:
        return "empty", {}
    u = conn.execute("SELECT module FROM codegen_units WHERE feature_key=?"
                     " AND status='active' LIMIT 1", (fk,)).fetchone()
    if not u:
        return "empty", {}
    module = u[0]
    conn.execute("UPDATE codegen_units SET body=? WHERE feature_key=? AND status='active'",
                 (body, fk))
    m = conn.execute("SELECT cbs_path, cbs_head FROM codegen_modules"
                     " WHERE feature_key=? AND module=?", (fk, module)).fetchone()
    if not m:                                   # single-module fallback (legacy row)
        m = conn.execute("SELECT cbs_path, cbs_head FROM codegen_modules"
                         " WHERE feature_key=? LIMIT 1", (fk,)).fetchone()
    if not m:
        return "empty", {}
    root = _worktree(ctx, task)
    _rebuild_cbs(conn, fk, module, root, m[0], m[1])
    return "ok", {"written": [str(root / m[0])], "module": module}


@block("codegen.mark_done", "state", {"ok"})
def codegen_mark_done(ctx, task, prev):
    """The active function compiled green -> mark it done and advance."""
    conn = ctx["_conn"]
    conn.execute("UPDATE codegen_units SET status='done'"
                 " WHERE feature_key=? AND status='active'", (_fk(task),))
    return "ok", {}


@block("codegen.retry_gate", "state", {"retry", "giveup"}, required_params={"cap"})
def codegen_retry_gate(ctx, task, prev):
    """The active function failed to compile. Bump its per-function attempt count
    and decide: regenerate ('retry') or give up ('giveup') once it exceeds `cap`.
    This is the PER-FUNCTION cap; the step's max_visits is only the global loop
    backstop (a module has many functions, so the loop steps run many times)."""
    conn = ctx["_conn"]
    fk = _fk(task)
    conn.execute("UPDATE codegen_units SET attempts = attempts + 1"
                 " WHERE feature_key=? AND status='active'", (fk,))
    row = conn.execute("SELECT contract_key, attempts FROM codegen_units"
                       " WHERE feature_key=? AND status='active' LIMIT 1", (fk,)).fetchone()
    cap = int(ctx["cap"])
    if row and row[1] > cap:
        return "giveup", {"contract_key": row[0], "attempts": row[1]}
    return "retry", {"contract_key": row[0] if row else None,
                     "attempts": row[1] if row else 0}
