"""codegen blocks — incremental, within-module code generation.

A module is generated as a frozen skeleton (the .hbs interface + a .cbs
preamble) produced ONCE, then one function body at a time, compiling after
each. This avoids the whole-file timeout (each gen is one small function) and
lets a compile error localize to — and regenerate — a single function instead
of the whole module. The .cbs is rebuilt from the accumulated bodies each write,
so regenerating a function REPLACES its body (no duplicate definitions).

  codegen.plan        group contracts into modules (units = modules)
  codegen.skel_write  persist + write the module skeleton (.hbs + .cbs head)
  codegen.seed_units  one codegen_units row per function (pending)
  codegen.next_fn     pick the next pending function -> active  (next | done)
  codegen.write_fn    store the active function's body, rebuild the .cbs
  codegen.mark_done   active -> done (its compile went green)
"""
from __future__ import annotations

from pathlib import Path

from forgeflow.blocks import block


def _fk(task):
    return (task.get("payload") or {}).get("feature_key")


def _worktree(ctx, task):
    """This task+attempt's worktree — the deterministic path worktree.create used."""
    return Path(ctx["_workspaces_dir"]) / ("task-%d-a%d" % (task["id"], task["attempts"]))


@block("codegen.plan", "state", {"ok", "empty"})
def codegen_plan(ctx, task, prev):
    """Group the feature's contracts into codegen UNITS = modules. Functions in
    one module share the struct, helpers, and internal calls, so a module is the
    smallest thing that can be generated coherently. A single-module feature is
    one unit (generated by the per-function loop below); a multi-module feature
    fans out one loop per module (fanout.emit + join — the identified
    enhancement, unneeded until a feature spans modules)."""
    conn = ctx["_conn"]
    rows = conn.execute(
        "SELECT c.module, c.impl_file FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.status='active'", (_fk(task),)).fetchall()
    mods = {}
    for m, impl in rows:
        mods[m or impl or "default"] = mods.get(m or impl or "default", 0) + 1
    if not mods:
        return "empty", {}
    units = [{"module": m, "contract_count": n} for m, n in sorted(mods.items())]
    return "ok", {"units": units, "unit_count": len(units)}


@block("codegen.skel_write", "state", {"ok", "empty"})
def codegen_skel_write(ctx, task, prev):
    """Persist the module skeleton (from the skeleton agent) and write the .hbs
    interface + the .cbs preamble into the worktree. Paths derive from the
    module's impl_file (.cbs) with .hbs alongside."""
    conn = ctx["_conn"]
    fk = _fk(task)
    hbs = (prev or {}).get("hbs")
    cbs_head = (prev or {}).get("cbs_head") or ""
    if not hbs:
        return "empty", {}
    r = conn.execute(
        "SELECT c.module, c.impl_file FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.impl_file IS NOT NULL LIMIT 1", (fk,)).fetchone()
    module = (r[0] if r else None) or "default"
    cbs_path = (r[1] if r else None) or ("src/%s.cbs" % module)
    hbs_path = cbs_path.rsplit(".", 1)[0] + ".hbs"
    # the skeleton agent tends to include by MODULE name; the file on disk
    # is derived from the impl path. When they differ the module can never
    # find its own header (hit live: '#include "cc_run.hbs"' vs
    # cc_run/exec.hbs — an env error no codegen agent can fix). Normalize
    # the first .hbs include to the file we actually write.
    import re as _re
    base = hbs_path.rsplit("/", 1)[-1]
    cbs_head = _re.sub(r'#include\s+"[^"]*\.hbs"', '#include "%s"' % base,
                       cbs_head, count=1)
    conn.execute("DELETE FROM codegen_modules WHERE feature_key=? AND module=?", (fk, module))
    conn.execute(
        "INSERT INTO codegen_modules(feature_key, module, hbs_path, cbs_path, hbs, cbs_head)"
        " VALUES (?,?,?,?,?,?)", (fk, module, hbs_path, cbs_path, hbs, cbs_head))
    root = _worktree(ctx, task)
    (root / hbs_path).parent.mkdir(parents=True, exist_ok=True)
    (root / hbs_path).write_text(hbs)
    (root / cbs_path).write_text(cbs_head.rstrip() + "\n")
    return "ok", {"module": module, "hbs_path": hbs_path, "cbs_path": cbs_path}


@block("codegen.need_skeleton", "state", {"build", "reuse"})
def codegen_need_skeleton(ctx, task, prev):
    """Is there a cached skeleton for this feature? 'reuse' on a modification
    (skeleton survived; reconcile drops it only on a signature change), 'build'
    on a first run or after a signature change."""
    row = ctx["_conn"].execute(
        "SELECT 1 FROM codegen_modules WHERE feature_key=?"
        " AND module != '__tests__' LIMIT 1", (_fk(task),)).fetchone()
    return ("reuse" if row else "build"), {}


def _rebuild_cbs(conn, fk, module, root, cbs_path, cbs_head):
    """.cbs = the module's preamble + that MODULE's bodies (never another's)."""
    bodies = [b for (b,) in conn.execute(
        "SELECT body FROM codegen_units WHERE feature_key=? AND module=?"
        " AND body IS NOT NULL ORDER BY seq", (fk, module))]
    cbs = cbs_head.rstrip() + ("\n\n" + "\n\n".join(b.strip() for b in bodies) + "\n"
                               if bodies else "\n")
    dest = root / cbs_path
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(cbs)
    return len(bodies)


@block("codegen.rehydrate", "state", {"ok", "empty"})
def codegen_rehydrate(ctx, task, prev):
    """A modification runs in a FRESH worktree. Restore EVERY cached module from
    the DB (its .hbs + a .cbs rebuilt from that module's done bodies), so the
    per-function loop only regenerates the units reconcile marked pending."""
    conn = ctx["_conn"]
    fk = _fk(task)
    rows = conn.execute("SELECT module, hbs_path, cbs_path, hbs, cbs_head"
                        " FROM codegen_modules WHERE feature_key=?", (fk,)).fetchall()
    if not rows:
        return "empty", {}
    root = _worktree(ctx, task)
    restored = 0
    for module, hbs_path, cbs_path, hbs, cbs_head in rows:
        (root / hbs_path).parent.mkdir(parents=True, exist_ok=True)
        (root / hbs_path).write_text(hbs)
        restored += _rebuild_cbs(conn, fk, module, root, cbs_path, cbs_head)
    return "ok", {"modules": len(rows), "rehydrated_bodies": restored}


@block("codegen.seed_units", "state", {"ok", "empty"})
def codegen_seed_units(ctx, task, prev):
    """Ensure a codegen_units row per active contract — IDEMPOTENT across runs:
    new contracts get a pending unit; existing units keep whatever status
    reconcile left (done stays done, changed is pending); contracts no longer
    active are dropped. This is what makes a modification re-gen only the deltas."""
    conn = ctx["_conn"]
    fk = _fk(task)
    rows = conn.execute(
        "SELECT c.contract_key, c.module FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.status='active' ORDER BY c.id", (fk,)).fetchall()
    if not rows:
        return "empty", {}
    existing = {ck for (ck,) in conn.execute(
        "SELECT contract_key FROM codegen_units WHERE feature_key=?", (fk,))}
    active = []
    for i, (ck, mod) in enumerate(rows):
        active.append(ck)
        if ck in existing:
            conn.execute("UPDATE codegen_units SET seq=? WHERE feature_key=? AND contract_key=?",
                         (i, fk, ck))
        else:
            conn.execute(
                "INSERT INTO codegen_units(feature_key, module, contract_key, seq, status)"
                " VALUES (?,?,?,?, 'pending')", (fk, mod or "default", ck, i))
    conn.execute("DELETE FROM codegen_units WHERE feature_key=? AND contract_key NOT IN (%s)"
                 % ",".join("?" * len(active)), [fk] + active)
    pending = conn.execute("SELECT count(*) FROM codegen_units"
                           " WHERE feature_key=? AND status='pending'", (fk,)).fetchone()[0]
    return "ok", {"units": len(rows), "pending": pending}


@block("codegen.next_fn", "state", {"next", "done"})
def codegen_next_fn(ctx, task, prev):
    """Advance the cursor: the current 'active' function (a red retry re-enters
    here only via mark_done, so normally none is active) or the next 'pending'
    one. 'done' when every unit is generated + compiled green."""
    conn = ctx["_conn"]
    fk = _fk(task)
    row = conn.execute(
        "SELECT contract_key FROM codegen_units WHERE feature_key=? AND status='active'"
        " ORDER BY seq LIMIT 1", (fk,)).fetchone()
    if not row:
        row = conn.execute(
            "SELECT contract_key FROM codegen_units WHERE feature_key=? AND status='pending'"
            " ORDER BY seq LIMIT 1", (fk,)).fetchone()
        if not row:
            return "done", {}
        conn.execute("UPDATE codegen_units SET status='active'"
                     " WHERE feature_key=? AND contract_key=?", (fk, row[0]))
    remaining = conn.execute(
        "SELECT count(*) FROM codegen_units WHERE feature_key=? AND status!='done'",
        (fk,)).fetchone()[0]
    # carry the active contract's text: every edge into gen_fn must provide the
    # select: query fields ({prev.summary} {prev.signature} — strict templating)
    meta = conn.execute(
        "SELECT c.summary, c.signature FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.contract_key=?", (fk, row[0])).fetchone()
    return "next", {"contract_key": row[0], "remaining": remaining,
                    "summary": (meta[0] if meta else "") or "",
                    "signature": (meta[1] if meta else "") or ""}


@block("codegen.write_fn", "state", {"ok", "empty"})
def codegen_write_fn(ctx, task, prev):
    """Store the active function's body, then rebuild ITS MODULE's .cbs from that
    module's bodies (never another module's). Rebuilding (vs appending) means a
    regenerate cleanly REPLACES the active function's body."""
    conn = ctx["_conn"]
    fk = _fk(task)
    body = (prev or {}).get("body")
    if not body:
        files = (prev or {}).get("files") or []
        body = files[0].get("content") if files and isinstance(files[0], dict) else None
    if not body:
        return "empty", {}
    u = conn.execute("SELECT module FROM codegen_units WHERE feature_key=?"
                     " AND status='active' LIMIT 1", (fk,)).fetchone()
    if not u:
        return "empty", {}
    module = u[0]
    conn.execute("UPDATE codegen_units SET body=? WHERE feature_key=? AND status='active'",
                 (body, fk))
    m = conn.execute("SELECT cbs_path, cbs_head FROM codegen_modules"
                     " WHERE feature_key=? AND module=?", (fk, module)).fetchone()
    if not m:                                   # single-module fallback (legacy row)
        m = conn.execute("SELECT cbs_path, cbs_head FROM codegen_modules"
                         " WHERE feature_key=? AND module != '__tests__'"
                         " LIMIT 1", (fk,)).fetchone()
    if not m:
        return "empty", {}
    root = _worktree(ctx, task)
    _rebuild_cbs(conn, fk, module, root, m[0], m[1])
    return "ok", {"written": [str(root / m[0])], "module": module}


@block("codegen.mark_done", "state", {"ok"})
def codegen_mark_done(ctx, task, prev):
    """The active function compiled green -> mark it done and advance. If it
    went red on the way (attempts > 0), record the (error -> body that fixed it)
    pair as a fix_lesson — the corpus fix_hints retrieves from later."""
    conn = ctx["_conn"]
    fk = _fk(task)
    u = conn.execute("SELECT contract_key, attempts, last_error, body FROM codegen_units"
                     " WHERE feature_key=? AND status='active' LIMIT 1", (fk,)).fetchone()
    lesson = 0
    if u and u[1] and u[2] and u[3]:            # fought the compiler and won
        conn.execute("INSERT INTO fix_lessons(feature_key, contract_key, error, body)"
                     " VALUES (?,?,?,?)", (fk, u[0], u[2][:2000], u[3]))
        lesson = 1
    conn.execute("UPDATE codegen_units SET status='done'"
                 " WHERE feature_key=? AND status='active'", (fk,))
    return "ok", {"lesson_recorded": lesson}


@block("codegen.retry_gate", "state", {"retry", "giveup"}, required_params={"cap"})
def codegen_retry_gate(ctx, task, prev):
    """The active function failed to compile. Bump its per-function attempt count
    and decide: regenerate ('retry') or give up ('giveup') once it exceeds `cap`.
    Also stash the compiler's error on the unit (last_error) — if this function
    later goes green, mark_done turns (error, fixed body) into a fix_lesson.
    This is the PER-FUNCTION cap; the step's max_visits is only the global loop
    backstop (a module has many functions, so the loop steps run many times)."""
    conn = ctx["_conn"]
    fk = _fk(task)
    err_text = None
    sp = (prev or {}).get("stderr_path")
    if sp and Path(sp).exists():
        err_text = Path(sp).read_text(errors="replace")[-2000:]
    conn.execute("UPDATE codegen_units SET attempts = attempts + 1, last_error ="
                 " COALESCE(?, last_error) WHERE feature_key=? AND status='active'",
                 (err_text, fk))
    row = conn.execute("SELECT contract_key, attempts FROM codegen_units"
                       " WHERE feature_key=? AND status='active' LIMIT 1", (fk,)).fetchone()
    cap = int(ctx["cap"])
    if row and row[1] > cap:
        return "giveup", {"contract_key": row[0], "attempts": row[1]}
    # the retry edge feeds gen_fn too: carry the same select: query fields
    meta = conn.execute(
        "SELECT c.summary, c.signature FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE s.feature_key=? AND c.contract_key=?",
        (fk, row[0] if row else "")).fetchone()
    return "retry", {"contract_key": row[0] if row else None,
                     "attempts": row[1] if row else 0,
                     "summary": (meta[0] if meta else "") or "",
                     "signature": (meta[1] if meta else "") or ""}


# ------------------------------------------------------------ surgical edits
#
# "Ask AI to change this function." The dividing line is the FROZEN INTERFACE
# (the contract hash's world): a body-only change re-enters the per-function
# loop (gen -> compile -> smoke) with no spec ceremony; a change that cannot
# fit the frozen signature/assertions surfaces as a human decision, and only
# a picked verdict escalates into the full requirement->spec->build pipeline.

@block("codegen.edit_route", "state", {"ok", "missing"})
def codegen_edit_route(ctx, task, prev):
    """fn.edit.requested carries only {contract_key, instruction} (the form
    lives on the function view, which knows no feature). Resolve the owning
    feature and re-emit fn.edit.routed WITH feature_key, so the edit task
    threads into its run on the board."""
    import time
    conn = ctx["_conn"]
    payload = task.get("payload") or {}
    ck = payload.get("contract_key")
    instruction = (payload.get("instruction") or "").strip()
    if not ck or not instruction:
        return "missing", {"error": "need contract_key + instruction"}
    r = conn.execute(
        "SELECT s.feature_key FROM contracts c JOIN specs s ON s.id = c.spec_id"
        " WHERE c.contract_key=? AND c.status='active' LIMIT 1", (ck,)).fetchone()
    if not r:
        return "missing", {"error": "no active contract '%s'" % ck}
    data = {"feature_key": r[0], "contract_key": ck,
            "instruction": instruction,
            "base": payload.get("base") or "main",
            "_force": time.time_ns()}          # a click IS intent: never dedup
    return "ok", {"feature_key": r[0],
                  "_staged": [{"op": "emit_event", "name": "fn.edit.routed",
                               "payload": data}]}


@block("codegen.edit_target", "state", {"ok", "missing"})
def codegen_edit_target(ctx, task, prev):
    """Arm the edit: the target function's unit becomes the ACTIVE cursor
    (the existing write_fn/compile/mark_done loop then operates on it),
    attempts reset so the edit gets a fresh per-function retry budget."""
    conn = ctx["_conn"]
    fk = _fk(task)
    ck = (task.get("payload") or {}).get("contract_key")
    u = conn.execute("SELECT status FROM codegen_units WHERE feature_key=?"
                     " AND contract_key=?", (fk, ck)).fetchone()
    if not u:
        return "missing", {"error": "no codegen unit for '%s' (feature never"
                                    " built?)" % ck}
    busy = conn.execute(
        "SELECT contract_key FROM codegen_units WHERE feature_key=?"
        " AND status='active' AND contract_key!=?", (fk, ck)).fetchone()
    if busy:
        return "missing", {"error": "another unit is active (%s) — a build is"
                                    " in flight; edit after it lands" % busy[0]}
    conn.execute("UPDATE codegen_units SET status='active', attempts=0,"
                 " last_error=NULL WHERE feature_key=? AND contract_key=?",
                 (fk, ck))
    return "ok", {"contract_key": ck}


@block("codegen.escalate", "state", {"ok", "missing"})
def codegen_escalate(ctx, task, prev):
    """The human confirmed the interface must change: hand the WHOLE run back
    to the full pipeline. Re-emits spec.requested with the stored requirement
    plus the edit instruction (edit_request) — decompose/fidelity keep the
    R-items honest, the author folds the change into the spec, reconcile
    ripples only what actually changed. Also release the armed unit."""
    import time
    conn = ctx["_conn"]
    fk = _fk(task)
    payload = task.get("payload") or {}
    r = conn.execute("SELECT requirement FROM specs WHERE feature_key=?",
                     (fk,)).fetchone()
    if not r:
        return "missing", {"error": "no spec for feature '%s'" % fk}
    conn.execute("UPDATE codegen_units SET status='done' WHERE feature_key=?"
                 " AND contract_key=? AND status='active'",
                 (fk, payload.get("contract_key")))
    data = {"feature_key": fk, "requirement": r[0],
            "base": payload.get("base") or "main",
            "tdd": payload.get("tdd") or "no",
            "edit_request": payload.get("instruction") or "",
            "_force": time.time_ns()}
    return "ok", {"_staged": [{"op": "emit_event", "name": "spec.requested",
                               "payload": data}]}


# ------------------------------------------------------------- optional TDD
#
# payload.tdd truthy -> AFTER the skeleton freezes the interface and BEFORE
# any body exists, an agent writes the feature's executable tests from the
# SPEC ALONE (implementation-blind by construction). The test file is
# syntax/ownership-checked against the frozen .hbs (the sound gate), stored
# as a pseudo-module (rehydrate restores it into every later worktree —
# including fn_edit's), and run by the same harness as the smoke test.

TESTS_MODULE = "__tests__"
TESTS_CBS = "tests/generated_tests.cbs"
TESTS_HBS = "tests/generated_tests.hbs"          # empty; rehydrate symmetry


@block("codegen.need_tests", "state", {"gen", "skip"})
def codegen_need_tests(ctx, task, prev):
    """The optional-TDD router: payload.tdd in yes/true/1/on -> generate
    spec-derived tests first; anything else -> straight to codegen."""
    v = str((task.get("payload") or {}).get("tdd") or "").strip().lower()
    return ("gen" if v in ("1", "true", "yes", "on", "tdd") else "skip"), \
        {"tdd": v or "no"}


@block("codegen.write_tests", "state", {"ok", "empty"})
def codegen_write_tests(ctx, task, prev):
    """Persist the generated test file as the __tests__ pseudo-module (so
    rehydrate restores it like any module) and write it into the worktree;
    `written` feeds the same verify.compile sound gate the bodies use."""
    conn = ctx["_conn"]
    fk = _fk(task)
    body = (prev or {}).get("body")
    if not body:
        return "empty", {}
    m = conn.execute(
        "SELECT hbs_path FROM codegen_modules WHERE feature_key=?"
        " AND module != ?", (fk, TESTS_MODULE)).fetchone()
    if m:
        # the tests live in tests/; the module's header does not. Rewrite
        # the first .hbs include to a path that resolves from there.
        import re as _re
        import posixpath
        rel = posixpath.relpath(m[0], TESTS_CBS.rsplit("/", 1)[0])
        body = _re.sub(r'#include\s+"[^"]*\.hbs"', '#include "%s"' % rel,
                       body, count=1)
    conn.execute("DELETE FROM codegen_modules WHERE feature_key=? AND module=?",
                 (fk, TESTS_MODULE))
    conn.execute(
        "INSERT INTO codegen_modules(feature_key, module, hbs_path, cbs_path,"
        " hbs, cbs_head) VALUES (?,?,?,?,?,?)",
        (fk, TESTS_MODULE, TESTS_HBS, TESTS_CBS, "", body))
    root = _worktree(ctx, task)
    (root / TESTS_CBS).parent.mkdir(parents=True, exist_ok=True)
    (root / TESTS_HBS).write_text("")
    (root / TESTS_CBS).write_text(body.rstrip() + "\n")
    scenarios = (prev or {}).get("scenarios") or []
    return "ok", {"written": [str(root / TESTS_CBS)], "scenarios": len(scenarios)}
